#!/bin/bash

set -e -o pipefail

BASE=$(dirname "$(readlink -fm "$0")")
KHADAS_TOOL="$BASE/toneboard-burn-tool"
RULES_DIR="$BASE/rules"
DISTRIB=$(cat /etc/lsb-release | grep "DISTRIB_ID" | awk -F "=" '{print $2}')
DISTRIB_RELEASE=$(cat /etc/lsb-release | grep "DISTRIB_RELEASE" | awk -F "=" '{print $2}')
INSTALL_DIR="/usr/local/bin"

RULE=

RED='\033[0;31m'
RESET='\033[m'

echo ""
echo "==============================================="
echo ""
echo "Host PC: $DISTRIB $DISTRIB_RELEASE"
echo ""
echo "==============================================="
echo ""

error_msg() {
	echo -e ${RED}Error:${RESET} $1
}

if [ "$DISTRIB" != "Ubuntu" ]; then
	error_msg "This burn tool just support Ubuntu now, other distributions haven't been verified!"
	exit 1
fi

echo "Installing USB rules..."

if [[ "$DISTRIB_RELEASE" =~ "16" || "$DISTRIB_RELEASE" =~ "18" || "$DISTRIB_RELEASE" =~ "20" ]]; then
	RULE="$RULES_DIR/80-toneboard-usb.rules"
	sudo cp $RULE /etc/udev/rules.d
else
	error_msg "Ubuntu $DISTRIB_RELEASE haven't been verified!"
	exit 1
fi

sudo udevadm control --reload-rules

echo "Installing toneboard-burn-tool..."
mkdir -p $INSTALL_DIR
sudo ln -fs $KHADAS_TOOL $INSTALL_DIR/$(basename $KHADAS_TOOL)

echo "Done!"
