#!/bin/bash

BASE=$(pwd)
RULES_DIR="$BASE/rules"
DISTRIB=$(cat /etc/lsb-release | grep "DISTRIB_ID" | awk -F "=" '{print $2}')
DISTRIB_RELEASE=$(cat /etc/lsb-release | grep "DISTRIB_RELEASE" | awk -F "=" '{print $2}')

RULE=

RED='\033[0;31m'
RESET='\033[m'

echo ""
echo "==============================================="
echo ""
echo "Host PC: $DISTRIB $DISTRIB_RELEASE"
echo ""
echo "==============================================="
echo ""

error_msg() {
	echo -e ${RED}Error:${RESET} $1
}

if [ "$DISTRIB" != "Ubuntu" ]; then
	error_msg "This flash tool just support Ubuntu now, other distributions haven't been verified!"
	exit 1
fi

echo "Install USB rules..."

if [[ "$DISTRIB_RELEASE" =~ "12" ]]; then
	RULE="$RULES_DIR/70-persistent-usb-ubuntu12.rules"
	sudo cp $RULE /etc/udev/rules.d
	sudo sed -i s/OWNER=\"amlogic\"/OWNER=\"`whoami`\"/g /etc/udev/rules.d/$(basename $RULE)
elif [[ "$DISTRIB_RELEASE" =~ "14" || "$DISTRIB_RELEASE" =~ "16" ]]; then
	RULE="$RULES_DIR/70-persistent-usb-ubuntu14.rules"
	sudo cp $RULE /etc/udev/rules.d
else
	error_msg "Ubuntu $DISTRIB_RELEASE haven't been verified!"
	exit 1
fi

sudo udevadm control --reload-rules


echo "Done!"
