#!/bin/bash

set -e -o pipefail

BASE=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

if [ "$(uname -s)" = "Darwin" ]; then
	DISTRIB=macOS
else
	DISTRIB=$(cat /etc/lsb-release | grep "DISTRIB_ID" | awk -F "=" '{print $2}')
	DISTRIB_RELEASE=$(cat /etc/lsb-release | grep "DISTRIB_RELEASE" | awk -F "=" '{print $2}')
fi

KHADAS_TOOL_NAME="rk-burn-tool"
INSTALL_DIR="/usr/local/bin"

RULE=

RED='\033[0;31m'
RESET='\033[m'

error_msg() {
	echo -e ${RED}Error:${RESET} $1
}

echo ""
echo "==============================================="
echo ""
echo "Host PC: $DISTRIB $DISTRIB_RELEASE"
echo ""
echo "==============================================="
echo ""

if [ "$DISTRIB" != "macOS" ]; then
	echo "Removing USB rules..."

	RULE="/etc/udev/rules.d/80-rockchip-usb.rules"

	sudo rm -f $RULE
	sudo udevadm control --reload-rules
fi

echo "Removing flash-tool..."
sudo rm -f $INSTALL_DIR/$KHADAS_TOOL_NAME

echo "Removing configuration..."
if [ -d ~/.config/upgrade_tool ]; then
	rm -r ~/.config/upgrade_tool
fi

echo "Done!"
