#!/bin/bash

set -e -o pipefail

FLASH_TOOL="$(dirname "$(readlink -fm "$0")")/flash-tool"
KHADAS_TOOL="/usr/local/bin/$(basename $0)"

IMAGE=
DEVICE=

RED='\033[0;31m'
RESET='\033[m'

error_msg() {
	echo -e "$RED"ERROR:"$RESET" $1
}

usage() {
	echo -e "Usage:"
	echo -e "emmc:   $0 -i <path-to-image>"
	echo -e "sdcard: $0 -d </dev/sdX> -i <path-to-image>"
}

flash_sdcard() {
	pv -tpreb ${IMAGE} | sudo dd of=${DEVICE} conv=notrunc
	echo "Sync..."
	sync
}

if [ ! -L $KHADAS_TOOL ]; then
	error_msg "Please install `basename $0`. Execute 'INSTALL' script to install it."
	exit 1
fi

while getopts "d:i:h" flag; do
	case $flag in
		d)
		DEVICE="$OPTARG"
		;;
		i)
		IMAGE="$OPTARG"
		;;
		h)
		usage
		exit
		;;
	esac
done

if [ ! -f "$IMAGE" ]; then
	error_msg "Image '$IMAGE' doesn't exist!"
	usage
	exit -1
fi

if [ $DEVICE ]; then
	if [ ! -b $DEVICE ]; then
		error_msg "'$DEVICE' is not a block device! Please make sure the device you choose is right."
		exit -1
	fi

	echo "Burning image '$IMAGE' to SD/USB storage..."
	flash_sdcard
else
	echo "Burning image '$IMAGE' to eMMC..."
	$FLASH_TOOL --img=$IMAGE --parts=all --wipe --soc=gxl --reset=y
fi
